knowage:
    image: knowagelabs/knowage-server-docker
    links:
        - knowagedb:db
    ports:
        - "8080:8080"
    environment:
        - WAIT_MYSQL=true

knowagedb:
    image: mysql:5.5
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
