knowage:
    image: knowagelabs/knowage-server-docker:develop
    links:
        - knowagedb:db
    environment:
        - WAIT_MYSQL=true

knowagedb:
    image: mysql:5.5
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
